name: Deploy Laravel Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to IONOS Server
        uses: appleboy/ssh-action@v1.0.0

        with:
          host: 212.227.146.242
          username: deploy
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACDKsmIrz8VvXD5KNK0YqfSwUptfJ08mjWvfLvTJSkfXdAAAAJC42SAOuNkg
            DgAAAAtzc2gtZWQyNTUxOQAAACDKsmIrz8VvXD5KNK0YqfSwUptfJ08mjWvfLvTJSkfXdA
            AAAEC6dJjYach6HCyf8R8ofUBhwKhH5+NJx64nthkORKuHMMqyYivPxW9cPko0rRip9LBS
            m18nTyaNa98u9MlKR9d0AAAADWRlcGxveS1naXRodWI=
            -----END OPENSSH PRIVATE KEY-----

          script: |
            cd /var/www/cb_SergioBonillo

            git pull origin main

            composer install --optimize-autoloader

            php artisan optimize:clear

            php artisan migrate --force

            php artisan config:cache

            php artisan route:cache

            php artisan view:cache
